### ISSUE TITLE
Cancelling of gis fetch and gis pull does not work as excpected

### ISSUE THREAD

**Issue by hoffmann-stefan** [Deleh/gis#3]
If you cancel `gis fetch` or `gis push` using `CTRL-C` already started git operations continue to run in the background. They should be cancelled as well and gis should only exit to the bash prompt if there will be no more output of background tasks.

**Comment by Deleh** [comment]
This should be fixed in https://github.com/Deleh/gis/commit/acc2344004a86efa8ca197c1213ca1112006d46f, feel free to try it and close the issue if everything works as expected.

**Comment by hoffmann-stefan** [comment]
Looks good 👍
