### ISSUE TITLE
readarray is not supported by zsh (osx)

### ISSUE THREAD

**Issue by benmaidel** [Deleh/gis#7]
readarray as used here: https://github.com/Deleh/gis/blob/master/gis#L92 is not supported on systems that only have zsh installed. Would be nice to use a different approach. See here: https://stackoverflow.com/questions/23842261/alternative-to-readarray-because-it-does-not-work-on-mac-os-x

**Comment by Deleh** [comment]
`radarray` was replaced with `read` in https://github.com/Deleh/gis/commit/8a340366bffa288eb735bdf4b125e7788e335018

**Comment by benmaidel** [comment]
thx @Deleh , works as a charm.
